### PR TITLE
Added delete user functionality to user_detail.php and controller.php

### PR DESCRIPTION
**Pull request by oschwartz10612**
I found myself wanting to be able to delete users so I thought I would add it.

I had to call a different delete function for the coach and delete from TEAM_COACH before USER because you have it referenceing USER_ID.

My apologies for the messed up spacing. I assume it is from going back and forth from the server.

### CODE REVIEW

**Review by Prestonjf — CHANGES_REQUESTED** [review]
When deleting a user, the user could be assigned to multiple roles. Every time a user would be deleted, there are several tables that need to have data removed from them when deleting. As a suggestion, you can use just one method for deletion, then perform all the necessary work to remove the data based on a users roles.  The following tables have links to a User. These links would need to be removed when deleting (so as to not orphan data):

1.  USER
2. USER_ROLE
3. TOURNAMENT_VERIFIER
4. TEAM_COACH
5. TOURNAMENT.ADMIN_USER_ID
6. TOURNAMENT_EVENT

You are welcome to try updating your pull request to make these checks. I can also put this on the project to-do list, and get to it when I can.

**Comment by oschwartz10612** [comment]
Okay, so I can't find TOURNAMENT.ADMIN_USER_ID. Below is what is in my database. 

+---------------------------+
| Tables_in_score_center_db |
+---------------------------+
| EVENT                     |
| REF_DATA                  |
| SCHEDULE_EVENT            |
| SCHEDULE_EVENT_PERIOD     |
| SCHEDULE_PERIOD           |
| SCHEDULE_TEAM             |
| TEAM                      |
| TEAM_COACH                |
| TEAM_EVENT_SCORE          |
| TOURNAMENT                |
| TOURNAMENT_EVENT          |
| TOURNAMENT_SCHEDULE       |
| TOURNAMENT_TEAM           |
| TOURNAMENT_VERIFIER       |
| USER                      |
| USER_LOGIN_LOG            |
| USER_ROLE                 |
+---------------------------+

Also, below is my new controller.php code. Is there anything I am missing and/or are they all correct?

`function deleteUser($mysqli, $id, $role) {
		if ($role == 'ADMIN') {
			$query = $mysqli->prepare("DELETE FROM TOURNAMENT.ADMIN_USER_ID WHERE USER_ID = '$id'");
			$query->execute();
			$query->free_result();
		}
		elseif ($role == 'SUPERVISOR') {
			$query = $mysqli->prepare("DELETE FROM TOURNAMENT_EVENT WHERE USER_ID = '$id'");
			$query->execute();
			$query->free_result();
		}
		elseif ($role == 'VERIFIER') {
			$query = $mysqli->prepare("DELETE FROM TOURNAMENT_VERIFIER WHERE USER_ID = '$id'");
			$query->execute();
			$query->free_result();
		}
		elseif ($role == 'COACH') {
			$query = $mysqli->prepare("DELETE FROM TEAM_COACH WHERE USER_ID = '$id'");
			$query->execute();
			$query->free_result();
		}
		$query = $mysqli->prepare("DELETE FROM USER_ROLE WHERE USER_ID = '$id'");
		$query->execute();
		$query->free_result();

		$query = $mysqli->prepare("DELETE FROM USER WHERE USER_ID = '$id'");
		$query->execute();
		$query->free_result();
	}`

Thanks,
Owen

**Comment by oschwartz10612** [comment]
There is an issue: user_detail.php redirects back to user.php but the entry in the table is not removed even if reloaded. You must click away from user.php and then back to get it to reload.

Any idea for a fix?

**Comment by Prestonjf** [comment]
There are still a few issues. I have written a delete user function (below) which should handle the "cleanup" / unlinking for a user, and finally user deletion. I would recommend removing the code to determine the role of the user. Deletion of every user should be handled the same way. The code below checks for any spot a user could currently be linked regardless of role. 

A couple notes:
1. We don't want to delete the entire Tournament record, we only want to unlink the (admin) user from the tournament. TOURNAMENT.ADMIN_USER_ID referred to the table, then column. Setting this column to null would unlink the user. The same goes for TOURNAMENT_EVENT.USER_ID. We don't want to delete an event that is linked to the tournament, but we do want to unlink the user that would serve as the supervisor for the event.

2. Adding all the statements (queries) into one query will save trips to the database. Just a best practice thing. A lot of the code is rather old and doesn't use best practices. This is one of the first projects I ever wrote.

3. The reason the user record displayed on user.php is because you have  window.history.back(); in user_detail.php, which will only take you to the previous page in the browser (where the user you are trying to delete is already loaded). After you finish running the "deleteUser" function, the list of users needs to be reloaded. Possibly with "loadAllUsers" function.  To keep the application consistent though, it may be better to not use AJAX, and instead, when the delete button is pressed, submit to a url that runs the delete function, reloads users and sets the page to user.php. (like the save or cancel button).

```	  
function deleteUser($mysqli, $id) {
		  $sql = "";
		  // Clean & Delete User Links
		  $sql .= "UPDATE TOURNAMENT SET ADMIN_USER_ID = null WHERE ADMIN_USER_ID = ".$id.";";
		  $sql .= "UPDATE TOURNAMENT_EVENT SET USER_ID = null WHERE USER_ID = ".$id.";";
		  $sql .= "DELETE FROM TOURNAMENT_VERIFIER WHERE USER_ID = ".$id.";";
		  $sql .= "DELETE FROM TEAM_COACH WHERE USER_ID = ".$id.";";
		  $sql .= "DELETE FROM USER_ROLE WHERE USER_ID = ".$id.";";
		  $sql .= "DELETE FROM USER_LOGIN_LOG WHERE USER_ID = ".$id.";";
		  	  
		  // Delete User
		  $sql .= "DELETE FROM USER WHERE USER_ID = ".$id.";";
		  
		  $query = $mysqli->multi_query($sql);  
	}
```

**Comment by oschwartz10612** [comment]
Thanks for the help. Obviously, this is only a hobby for me, so I am doing my best.

I am slightly confused by the workings of the Cancel and Save buttons. I added a session variable for the success message, but from there I am not sure.

**Comment by oschwartz10612** [comment]
Thanks for the help. Obviously, this is only a hobby for me so I am making it up as I go along.

I have implemented the changes your suggestions. The only problem now is it seems not to show all of the users (table is blank) when it redirects back to the main page. I can't quite figure this out.

**Comment by Prestonjf** [comment]
I went ahead and merged in your changes, but I also made some modifications. I added additional code for the deleteUser function in the controller.php to free the results. This should allow the user.php page to load after deletion. I updated user_detail.php with a javascript confirmation for delete and to submit the form.

Please update from my branch controller.php and user_detail.php.

I don't normally spend a lot of time on this project. Most new features I will probably want to review and write myself.

**Comment by Prestonjf** [comment]
I appreciate you taking the time to work with the code. I see you have the code forked into your own repository. Feel free to make additional code changes and try them out there! I wish I had more time to work on this project, but I don't have a lot of time for active development on this.

**Comment by Prestonjf** [comment]
Sorry, forgot to add an ID for the "form" tag in user_detail.php.

Update the file and you should be good. Just missed that when merging the code.

**Comment by oschwartz10612** [comment]
No problem. Thanks for indulging my interests.

Owen

**Pull request merged**
